jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install Wire
        run: go install github.com/google/wire/cmd/wire@latest

      - name: Generate Wire
        run: wire ./internal/infrastructure/wire/...

      - name: Run tests
        run: go test -v ./...

      - name: Build main.exe
        run: go build -o ./bin/main.exe cmd/app/main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-exe
          path: ./bin/main.exe
